find_and_upload_receipts:
  description: >
    Find and upload receipts for deductible business expenses in the Downloads folder and upload them to the Google Drive.
  expected_output: >
    The name of the receipt file and whether the receipt was successfully uploaded to the Google Drive.
  agent: receipt_manager
